apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  # Contraseñas
  POSTGRES_PASSWORD: "changethis"
  SECRET_KEY: "changethis123456"
  FIRST_SUPERUSER_PASSWORD: "changethis"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  # Variables de entorno
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "app"
  POSTGRES_SERVER: "postgres-service"
  DOMAIN: "localhost"
  FIRST_SUPERUSER: "admin@example.com"
  
  # --- ESTA ES LA LÍNEA QUE FALTABA ---
  PROJECT_NAME: "Full Stack FastAPI Project"
  # ------------------------------------